function [fitresult, gof] = createFit(n, X)
%CREATEFIT(N,X)
%  Create a fit.
%
%  Data for 'position fit 1' fit:
%      X Input : n
%      Y Output: X
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Nov-2019 16:23:08


%% Fit: 'position fit 1'.
[xData, yData] = prepareCurveData( n, X );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'position fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'X vs. n', 'position fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel n
ylabel X
grid on


