subplot(3,1,1)
plot(sara(:,1), sara(:,2))
title('Arm current')
xlabel('Time')
subplot(3,1,2)
plot(sara(:,1), sara(:,3))
title('Position')
xlabel('Time')
subplot(3,1,3)
plot(sara(:,1), sara(:,4))
title('Speed')
xlabel('Time')
